# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ownership_cache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/ownership_cache.proto',
  package='mg.protocol.ownership_cache',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1cprotos/ownership_cache.proto\x12\x1bmg.protocol.ownership_cache\"\xf2\x06\n\tOwnedGame\x12\x12\n\nproduct_id\x18\x01 \x02(\r\x12\x10\n\x08uplay_id\x18\x02 \x01(\r\x12\x13\n\x0b\x64ownload_id\x18\t \x01(\r\x12\x10\n\x08orbit_id\x18\x03 \x01(\r\x12\x0e\n\x06\x63\x64_key\x18\x04 \x01(\t\x12\x10\n\x08platform\x18\x05 \x01(\r\x12\x14\n\x0cproduct_type\x18\x06 \x01(\r\x12\r\n\x05state\x18\x07 \x01(\r\x12\x1c\n\x14product_associations\x18\x08 \x03(\r\x12\x11\n\tgame_code\x18\n \x01(\t\x12\x10\n\x08\x62rand_id\x18\x0b \x01(\r\x12$\n\x1cpending_keystorage_ownership\x18\x0c \x01(\x08\x12\x17\n\x0flegacy_space_id\x18\r \x01(\t\x12\x15\n\rlegacy_app_id\x18\x0e \x01(\t\x12\x12\n\ngame_token\x18\x0f \x01(\t\x12\x16\n\x0e\x61\x63tivation_ids\x18\x10 \x03(\r\x12L\n\x0etarget_partner\x18\x11 \x01(\x0e\x32\x34.mg.protocol.ownership_cache.OwnedGame.TargetPartner\x12N\n\x0f\x61\x63tivation_type\x18\x12 \x01(\x0e\x32\x35.mg.protocol.ownership_cache.OwnedGame.ActivationType\x12\x1a\n\x12ubiServices_app_id\x18\x13 \x01(\t\"D\n\rTargetPartner\x12\x16\n\x12TargetPartner_None\x10\x00\x12\x1b\n\x17TargetPartner_EpicGames\x10\x01\"h\n\x0e\x41\x63tivationType\x12\x1b\n\x17\x41\x63tivationType_Purchase\x10\x00\x12\x18\n\x14\x41\x63tivationType_Trial\x10\x01\x12\x1f\n\x1b\x41\x63tivationType_Subscription\x10\x02\"\xa1\x01\n\x0cPackageState\x12\x1c\n\x18PackageState_Unavailable\x10\x00\x12\x1c\n\x18PackageState_PreReleased\x10\x01\x12 \n\x1cPackageState_PreDownloadable\x10\x02\x12\x19\n\x15PackageState_Released\x10\x03\x12\x18\n\x14PackageState_Expired\x10\x04\"b\n\x0eOwnershipCache\x12;\n\x0bowned_games\x18\x01 \x03(\x0b\x32&.mg.protocol.ownership_cache.OwnedGame\x12\x13\n\x0bproduct_ids\x18\x02 \x03(\r')
)



_OWNEDGAME_TARGETPARTNER = _descriptor.EnumDescriptor(
  name='TargetPartner',
  full_name='mg.protocol.ownership_cache.OwnedGame.TargetPartner',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TargetPartner_None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TargetPartner_EpicGames', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=606,
  serialized_end=674,
)
_sym_db.RegisterEnumDescriptor(_OWNEDGAME_TARGETPARTNER)

_OWNEDGAME_ACTIVATIONTYPE = _descriptor.EnumDescriptor(
  name='ActivationType',
  full_name='mg.protocol.ownership_cache.OwnedGame.ActivationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ActivationType_Purchase', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ActivationType_Trial', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ActivationType_Subscription', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=676,
  serialized_end=780,
)
_sym_db.RegisterEnumDescriptor(_OWNEDGAME_ACTIVATIONTYPE)

_OWNEDGAME_PACKAGESTATE = _descriptor.EnumDescriptor(
  name='PackageState',
  full_name='mg.protocol.ownership_cache.OwnedGame.PackageState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PackageState_Unavailable', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PackageState_PreReleased', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PackageState_PreDownloadable', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PackageState_Released', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PackageState_Expired', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=783,
  serialized_end=944,
)
_sym_db.RegisterEnumDescriptor(_OWNEDGAME_PACKAGESTATE)


_OWNEDGAME = _descriptor.Descriptor(
  name='OwnedGame',
  full_name='mg.protocol.ownership_cache.OwnedGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='mg.protocol.ownership_cache.OwnedGame.product_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uplay_id', full_name='mg.protocol.ownership_cache.OwnedGame.uplay_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='download_id', full_name='mg.protocol.ownership_cache.OwnedGame.download_id', index=2,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orbit_id', full_name='mg.protocol.ownership_cache.OwnedGame.orbit_id', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cd_key', full_name='mg.protocol.ownership_cache.OwnedGame.cd_key', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='mg.protocol.ownership_cache.OwnedGame.platform', index=5,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_type', full_name='mg.protocol.ownership_cache.OwnedGame.product_type', index=6,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='mg.protocol.ownership_cache.OwnedGame.state', index=7,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_associations', full_name='mg.protocol.ownership_cache.OwnedGame.product_associations', index=8,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_code', full_name='mg.protocol.ownership_cache.OwnedGame.game_code', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brand_id', full_name='mg.protocol.ownership_cache.OwnedGame.brand_id', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pending_keystorage_ownership', full_name='mg.protocol.ownership_cache.OwnedGame.pending_keystorage_ownership', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='legacy_space_id', full_name='mg.protocol.ownership_cache.OwnedGame.legacy_space_id', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='legacy_app_id', full_name='mg.protocol.ownership_cache.OwnedGame.legacy_app_id', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_token', full_name='mg.protocol.ownership_cache.OwnedGame.game_token', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_ids', full_name='mg.protocol.ownership_cache.OwnedGame.activation_ids', index=15,
      number=16, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_partner', full_name='mg.protocol.ownership_cache.OwnedGame.target_partner', index=16,
      number=17, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_type', full_name='mg.protocol.ownership_cache.OwnedGame.activation_type', index=17,
      number=18, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ubiServices_app_id', full_name='mg.protocol.ownership_cache.OwnedGame.ubiServices_app_id', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OWNEDGAME_TARGETPARTNER,
    _OWNEDGAME_ACTIVATIONTYPE,
    _OWNEDGAME_PACKAGESTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=944,
)


_OWNERSHIPCACHE = _descriptor.Descriptor(
  name='OwnershipCache',
  full_name='mg.protocol.ownership_cache.OwnershipCache',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owned_games', full_name='mg.protocol.ownership_cache.OwnershipCache.owned_games', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_ids', full_name='mg.protocol.ownership_cache.OwnershipCache.product_ids', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=946,
  serialized_end=1044,
)

_OWNEDGAME.fields_by_name['target_partner'].enum_type = _OWNEDGAME_TARGETPARTNER
_OWNEDGAME.fields_by_name['activation_type'].enum_type = _OWNEDGAME_ACTIVATIONTYPE
_OWNEDGAME_TARGETPARTNER.containing_type = _OWNEDGAME
_OWNEDGAME_ACTIVATIONTYPE.containing_type = _OWNEDGAME
_OWNEDGAME_PACKAGESTATE.containing_type = _OWNEDGAME
_OWNERSHIPCACHE.fields_by_name['owned_games'].message_type = _OWNEDGAME
DESCRIPTOR.message_types_by_name['OwnedGame'] = _OWNEDGAME
DESCRIPTOR.message_types_by_name['OwnershipCache'] = _OWNERSHIPCACHE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OwnedGame = _reflection.GeneratedProtocolMessageType('OwnedGame', (_message.Message,), dict(
  DESCRIPTOR = _OWNEDGAME,
  __module__ = 'protos.ownership_cache_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.ownership_cache.OwnedGame)
  ))
_sym_db.RegisterMessage(OwnedGame)

OwnershipCache = _reflection.GeneratedProtocolMessageType('OwnershipCache', (_message.Message,), dict(
  DESCRIPTOR = _OWNERSHIPCACHE,
  __module__ = 'protos.ownership_cache_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.ownership_cache.OwnershipCache)
  ))
_sym_db.RegisterMessage(OwnershipCache)


# @@protoc_insertion_point(module_scope)
