# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/uplay_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/uplay_service.proto',
  package='mg.protocol.uplay_service',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1aprotos/uplay_service.proto\x12\x19mg.protocol.uplay_service\" \n\x0cStartInstall\x12\x10\n\x08uplay_id\x18\x01 \x02(\r\"[\n\x14InstallingDependency\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12\x14\n\x0cindex_number\x18\x02 \x02(\r\x12\x18\n\x10installers_count\x18\x03 \x02(\r\"V\n\x13\x44\x65pendencyInstalled\x12\x14\n\x0cinstaller_id\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\r\x12\x18\n\x10restart_required\x18\x03 \x02(\x08\",\n\x10InstallCompleted\x12\x18\n\x10restart_required\x18\x01 \x02(\x08\"\x1c\n\nGearResult\x12\x0e\n\x06result\x18\x01 \x02(\t\"\xe7\x02\n\x03Req\x12>\n\rstart_install\x18\x01 \x01(\x0b\x32\'.mg.protocol.uplay_service.StartInstall\x12N\n\x15installing_dependency\x18\x02 \x01(\x0b\x32/.mg.protocol.uplay_service.InstallingDependency\x12L\n\x14\x64\x65pendency_installed\x18\x03 \x01(\x0b\x32..mg.protocol.uplay_service.DependencyInstalled\x12\x46\n\x11install_completed\x18\x04 \x01(\x0b\x32+.mg.protocol.uplay_service.InstallCompleted\x12:\n\x0bgear_result\x18\x05 \x01(\x0b\x32%.mg.protocol.uplay_service.GearResult\"+\n\x14\x44\x65pendencyRestartRsp\x12\x13\n\x0bis_approved\x18\x01 \x01(\x08\"G\n\x03Rsp\x12@\n\x07restart\x18\x01 \x01(\x0b\x32/.mg.protocol.uplay_service.DependencyRestartRsp\"\x13\n\x11\x43\x61ncelInstallPush\"L\n\x04Push\x12\x44\n\x0e\x63\x61ncel_install\x18\x01 \x01(\x0b\x32,.mg.protocol.uplay_service.CancelInstallPush\"7\n\x08Upstream\x12+\n\x03req\x18\x01 \x01(\x0b\x32\x1e.mg.protocol.uplay_service.Req\"h\n\nDownstream\x12+\n\x03rsp\x18\x01 \x01(\x0b\x32\x1e.mg.protocol.uplay_service.Rsp\x12-\n\x04push\x18\x02 \x01(\x0b\x32\x1f.mg.protocol.uplay_service.Push')
)




_STARTINSTALL = _descriptor.Descriptor(
  name='StartInstall',
  full_name='mg.protocol.uplay_service.StartInstall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uplay_id', full_name='mg.protocol.uplay_service.StartInstall.uplay_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=89,
)


_INSTALLINGDEPENDENCY = _descriptor.Descriptor(
  name='InstallingDependency',
  full_name='mg.protocol.uplay_service.InstallingDependency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='mg.protocol.uplay_service.InstallingDependency.description', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_number', full_name='mg.protocol.uplay_service.InstallingDependency.index_number', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='installers_count', full_name='mg.protocol.uplay_service.InstallingDependency.installers_count', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=182,
)


_DEPENDENCYINSTALLED = _descriptor.Descriptor(
  name='DependencyInstalled',
  full_name='mg.protocol.uplay_service.DependencyInstalled',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='installer_id', full_name='mg.protocol.uplay_service.DependencyInstalled.installer_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='mg.protocol.uplay_service.DependencyInstalled.version', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restart_required', full_name='mg.protocol.uplay_service.DependencyInstalled.restart_required', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=270,
)


_INSTALLCOMPLETED = _descriptor.Descriptor(
  name='InstallCompleted',
  full_name='mg.protocol.uplay_service.InstallCompleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='restart_required', full_name='mg.protocol.uplay_service.InstallCompleted.restart_required', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=316,
)


_GEARRESULT = _descriptor.Descriptor(
  name='GearResult',
  full_name='mg.protocol.uplay_service.GearResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='mg.protocol.uplay_service.GearResult.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=346,
)


_REQ = _descriptor.Descriptor(
  name='Req',
  full_name='mg.protocol.uplay_service.Req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_install', full_name='mg.protocol.uplay_service.Req.start_install', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='installing_dependency', full_name='mg.protocol.uplay_service.Req.installing_dependency', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dependency_installed', full_name='mg.protocol.uplay_service.Req.dependency_installed', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='install_completed', full_name='mg.protocol.uplay_service.Req.install_completed', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gear_result', full_name='mg.protocol.uplay_service.Req.gear_result', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=708,
)


_DEPENDENCYRESTARTRSP = _descriptor.Descriptor(
  name='DependencyRestartRsp',
  full_name='mg.protocol.uplay_service.DependencyRestartRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_approved', full_name='mg.protocol.uplay_service.DependencyRestartRsp.is_approved', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=710,
  serialized_end=753,
)


_RSP = _descriptor.Descriptor(
  name='Rsp',
  full_name='mg.protocol.uplay_service.Rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='restart', full_name='mg.protocol.uplay_service.Rsp.restart', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=755,
  serialized_end=826,
)


_CANCELINSTALLPUSH = _descriptor.Descriptor(
  name='CancelInstallPush',
  full_name='mg.protocol.uplay_service.CancelInstallPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=828,
  serialized_end=847,
)


_PUSH = _descriptor.Descriptor(
  name='Push',
  full_name='mg.protocol.uplay_service.Push',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cancel_install', full_name='mg.protocol.uplay_service.Push.cancel_install', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=849,
  serialized_end=925,
)


_UPSTREAM = _descriptor.Descriptor(
  name='Upstream',
  full_name='mg.protocol.uplay_service.Upstream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='mg.protocol.uplay_service.Upstream.req', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=927,
  serialized_end=982,
)


_DOWNSTREAM = _descriptor.Descriptor(
  name='Downstream',
  full_name='mg.protocol.uplay_service.Downstream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rsp', full_name='mg.protocol.uplay_service.Downstream.rsp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='push', full_name='mg.protocol.uplay_service.Downstream.push', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=984,
  serialized_end=1088,
)

_REQ.fields_by_name['start_install'].message_type = _STARTINSTALL
_REQ.fields_by_name['installing_dependency'].message_type = _INSTALLINGDEPENDENCY
_REQ.fields_by_name['dependency_installed'].message_type = _DEPENDENCYINSTALLED
_REQ.fields_by_name['install_completed'].message_type = _INSTALLCOMPLETED
_REQ.fields_by_name['gear_result'].message_type = _GEARRESULT
_RSP.fields_by_name['restart'].message_type = _DEPENDENCYRESTARTRSP
_PUSH.fields_by_name['cancel_install'].message_type = _CANCELINSTALLPUSH
_UPSTREAM.fields_by_name['req'].message_type = _REQ
_DOWNSTREAM.fields_by_name['rsp'].message_type = _RSP
_DOWNSTREAM.fields_by_name['push'].message_type = _PUSH
DESCRIPTOR.message_types_by_name['StartInstall'] = _STARTINSTALL
DESCRIPTOR.message_types_by_name['InstallingDependency'] = _INSTALLINGDEPENDENCY
DESCRIPTOR.message_types_by_name['DependencyInstalled'] = _DEPENDENCYINSTALLED
DESCRIPTOR.message_types_by_name['InstallCompleted'] = _INSTALLCOMPLETED
DESCRIPTOR.message_types_by_name['GearResult'] = _GEARRESULT
DESCRIPTOR.message_types_by_name['Req'] = _REQ
DESCRIPTOR.message_types_by_name['DependencyRestartRsp'] = _DEPENDENCYRESTARTRSP
DESCRIPTOR.message_types_by_name['Rsp'] = _RSP
DESCRIPTOR.message_types_by_name['CancelInstallPush'] = _CANCELINSTALLPUSH
DESCRIPTOR.message_types_by_name['Push'] = _PUSH
DESCRIPTOR.message_types_by_name['Upstream'] = _UPSTREAM
DESCRIPTOR.message_types_by_name['Downstream'] = _DOWNSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartInstall = _reflection.GeneratedProtocolMessageType('StartInstall', (_message.Message,), dict(
  DESCRIPTOR = _STARTINSTALL,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.StartInstall)
  ))
_sym_db.RegisterMessage(StartInstall)

InstallingDependency = _reflection.GeneratedProtocolMessageType('InstallingDependency', (_message.Message,), dict(
  DESCRIPTOR = _INSTALLINGDEPENDENCY,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.InstallingDependency)
  ))
_sym_db.RegisterMessage(InstallingDependency)

DependencyInstalled = _reflection.GeneratedProtocolMessageType('DependencyInstalled', (_message.Message,), dict(
  DESCRIPTOR = _DEPENDENCYINSTALLED,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.DependencyInstalled)
  ))
_sym_db.RegisterMessage(DependencyInstalled)

InstallCompleted = _reflection.GeneratedProtocolMessageType('InstallCompleted', (_message.Message,), dict(
  DESCRIPTOR = _INSTALLCOMPLETED,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.InstallCompleted)
  ))
_sym_db.RegisterMessage(InstallCompleted)

GearResult = _reflection.GeneratedProtocolMessageType('GearResult', (_message.Message,), dict(
  DESCRIPTOR = _GEARRESULT,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.GearResult)
  ))
_sym_db.RegisterMessage(GearResult)

Req = _reflection.GeneratedProtocolMessageType('Req', (_message.Message,), dict(
  DESCRIPTOR = _REQ,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.Req)
  ))
_sym_db.RegisterMessage(Req)

DependencyRestartRsp = _reflection.GeneratedProtocolMessageType('DependencyRestartRsp', (_message.Message,), dict(
  DESCRIPTOR = _DEPENDENCYRESTARTRSP,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.DependencyRestartRsp)
  ))
_sym_db.RegisterMessage(DependencyRestartRsp)

Rsp = _reflection.GeneratedProtocolMessageType('Rsp', (_message.Message,), dict(
  DESCRIPTOR = _RSP,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.Rsp)
  ))
_sym_db.RegisterMessage(Rsp)

CancelInstallPush = _reflection.GeneratedProtocolMessageType('CancelInstallPush', (_message.Message,), dict(
  DESCRIPTOR = _CANCELINSTALLPUSH,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.CancelInstallPush)
  ))
_sym_db.RegisterMessage(CancelInstallPush)

Push = _reflection.GeneratedProtocolMessageType('Push', (_message.Message,), dict(
  DESCRIPTOR = _PUSH,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.Push)
  ))
_sym_db.RegisterMessage(Push)

Upstream = _reflection.GeneratedProtocolMessageType('Upstream', (_message.Message,), dict(
  DESCRIPTOR = _UPSTREAM,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.Upstream)
  ))
_sym_db.RegisterMessage(Upstream)

Downstream = _reflection.GeneratedProtocolMessageType('Downstream', (_message.Message,), dict(
  DESCRIPTOR = _DOWNSTREAM,
  __module__ = 'protos.uplay_service_pb2'
  # @@protoc_insertion_point(class_scope:mg.protocol.uplay_service.Downstream)
  ))
_sym_db.RegisterMessage(Downstream)


# @@protoc_insertion_point(module_scope)
